CREATE DATABASE IF NOT EXISTS DBUI;
USE DBUI;
CREATE TABLE IF NOT EXISTS users(
  user_id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  admin BOOLEAN NOT NULL DEFAULT FALSE
);
CREATE TABLE IF NOT EXISTS profiles(
  profile_id INT NOT NULL,
  bio VARCHAR(1000),
  carma INT DEFAULT 0
);
CREATE TABLE IF NOT EXISTS posts(
  post_id INT AUTO_INCREMENT PRIMARY KEY,
  author VARCHAR(255) NOT NULL,
  garage VARCHAR(255) NOT NULL,
  title VARCHAR(255) NOT NULL,
  content VARCHAR(2000) NOT NULL,
  parent INT DEFAULT NULL,
  rating INT DEFAULT 0
);
CREATE TABLE IF NOT EXISTS garages(
  garage_id INT AUTO_INCREMENT PRIMARY KEY,
  creator VARCHAR(255) NOT NULL,
  name VARCHAR(100) NOT NULL,
  description VARCHAR(1000) NOT NULL,
  num_posts INT DEFAULT 0
);
CREATE TABLE IF NOT EXISTS memberships(
  garage_id INT PRIMARY KEY,
  member_id INT NOT NULL
);
CREATE TABLE IF NOT EXISTS awards(
  award_type INT NOT NULL,
  donor_id INT NOT NULL,
  recipient_id INT NOT NULL,
  post_id INT NOT NULL
);
CREATE TABLE IF NOT EXISTS likes(user_id INT NOT NULL, post_id INT NOT NULL);